# Generated by Django 5.0.6 on 2024-07-11 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0002_blogmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('student_id', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('出席', '出席'), ('欠席', '欠席'), ('遅刻', '遅刻')], max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='BlogModel',
        ),
        migrations.DeleteModel(
            name='SampleModel',
        ),
    ]
